services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - ./data:/data
    restart: always

  db:
    container_name: postgres-db
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  email-service:
    build: ./email-service
    container_name: email-service
    ports:
      - 3000:3000
    depends_on:
      - redis
    env_file:
      - ./email-service/.env
    networks:
      - app-network
    restart: always

  email-sender:
    build:
      context: ./email-sender
    container_name: email-sender
    ports:
      - 5173:5173
    env_file:
      - ./email-sender/.env
    networks:
      - app-network
    depends_on:
      - email-service
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-db:
    external: false
